# Database
spring.datasource.url=jdbc:mysql://localhost:3306/vviet_campus
spring.datasource.username=root
spring.datasource.password=root123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server
server.port=8080

# App name
spring.application.name=campus
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration